### ISSUE TITLE
running into issues with windows 10

### ISSUE THREAD

**Issue by lawrenceong001** [MauriceGit/Voronoi_Image_Manipulation#3]
hi,

trying to execute 'go get ./...' after installing the latest go and cygwin64. 

getting this error..: 
collect2: error: ld returned 1 exit status
go: failed to remove work dir: GetFileInformationByHandle C:\cygwin64\tmp\go-build400702038\NUL: Incorrect function.

apologies as I'm not a go guy at all. any help?

tks
Lawrence

**Comment by lawrenceong001** [comment]
hi again,

after rereading your notes, I switched to downloading and running [mingw-w64](https://sourceforge.net/projects/mingw-w64/) instead. I still get errors, but the messaging is now a bit different:

`# github.com/go-gl/glfw/v3.2/glfw`
`In file included from ..\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:0:`
`..\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function ‘createMonitor’:`
`..\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function ‘wcscpy’; did you mean ‘stpcpy’? [-Wimplicit-function-declaration]`
`     wcscpy(monitor->win32.adapterName, adapter->DeviceName);`
`     ^~~~~~`
`     stpcpy`
`..\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function` `‘_glfwPlatformIsSameMonitor’:`
`..\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function ‘wcslen’; did you mean ‘scalbn’? [-Wimplicit-function-declaration]`
`     if (wcslen(first->win32.displayName))`
`         ^~~~~~`
`         scalbn`
`..\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function ‘wcscmp’; did you mean ‘wctomb’? [-Wimplicit-function-declaration]`
`         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;`
`                ^~~~~~`
`                wctomb`
`# Voronoi_Image_Manipulation`
`c:\go\pkg\tool\windows_amd64\link.exe: running g++ failed: exit status 1`
`C:\Users\a_ongl\AppData\Local\Temp\go-link-110908711\000044.o: In function glfwSwapBuffers':`
`C:\Users\a_ongl\go\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:609: undefined reference to __assert_func'`
`C:\Users\a_ongl\AppData\Local\Temp\go-link-110908711\000044.o: In function glfwExtensionSupported':`
`C:\Users\a_ongl\go\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:642: undefined reference to __assert_func'`
`C:\Users\a_ongl\AppData\Local\Temp\go-link-110908711\000044.o: In function glfwGetProcAddress':`
`C:\Users\a_ongl\go\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:707: undefined reference to __assert_func'`
`C:\Users\a_ongl\AppData\Local\Temp\go-link-110908711\000044.o: In function glfwGetInputMode':`
`C:\Users\a_ongl\go\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:153: undefined reference to __assert_func'`
`C:\Users\a_ongl\AppData\Local\Temp\go-link-110908711\000044.o: In function glfwSetInputMode':`
`C:\Users\a_ongl\go\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:174: undefined reference to __assert_func'`
`C:\Users\a_ongl\AppData\Local\Temp\go-link-110908711\000044.o:C:\Users\a_ongl\go\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:262: more undefined references to __assert_func' follow`
`collect2.exe: error: ld returned 1 exit status`


go version:
`go version go1.13.4 windows/amd64`

gcc version:
`gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0`
`Copyright (C) 2018 Free Software Foundation, Inc.`
`This is free software; see the source for copying conditions.  There is NO`
`warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Windows version: 
`Microsoft Windows [Version 10.0.17134.1069]`

running from standard command prompt.

any suggestions? 

thanks
Lawrence

**Comment by MauriceGit** [comment]
Is this issue also solved?
How did you get around this?

**Comment by lawrenceong001** [comment]
hi Maurice,

this was done on my 6 year old work computer, with all kinds of proxies and firewall restrictions, so the fact that I can actually get it to run on my computer tells me that this may not be related with your application.

tks
lawrence

**Comment by MauriceGit** [comment]
Alright, I close it for now, feel free to reopen if necessary!
