### ISSUE TITLE
Cannot install or build :/

### ISSUE THREAD

**Issue by RMX0** [MauriceGit/Voronoi_Image_Manipulation#8]
Hi, 

I tried to install and run it, but ran into the following issues: 

<img width="990" alt="Screenshot 2021-01-04 at 23 33 09" src="https://user-images.githubusercontent.com/44804023/103586640-cbe21200-4ee5-11eb-845a-e439ea3cbe2b.png">
<img width="1049" alt="Screenshot 2021-01-04 at 23 32 52" src="https://user-images.githubusercontent.com/44804023/103586661-d56b7a00-4ee5-11eb-9347-7969ebd90726.png">

Do you maybe know how to resolve this issue?

Kind regards

**Comment by MauriceGit** [comment]
Hi,

Yes, I think I know the issue. Did you install the following packages: libgl1-mesa-dev ?
I found this post with some more information: https://stackoverflow.com/questions/65387167/glfw-pkg-config-error-when-building-a-fyne-app

(sudo apt-get install libgl1-mesa-dev)

If it still doesn't work with libgl1-mesa-dev, try also installing 'xorg-dev'.

Please report back, if it worked :)

**Comment by RMX0** [comment]
Thank you very much. I will try to install tomorrow and report whether it worked :) 
Do you maybe know if I need to install anything else? I use Mac OS Big Sur and and Kali Linux (Debian)? I am also not very familiar with Go so I just ran go get ./...

Kind regards, 
Roman

**Comment by MauriceGit** [comment]
There might be some more packages, but I am not sure right now. 
Do you have a graphics card that supports OpenGL 4.3? I do use some features of 4.3.

Start with libgl1-mesa-dev and xorg-dev and we'll go from there.

**Comment by RMX0** [comment]
Hi Maurice,

shank you for your help! I installed both packages and the window popped up. However, I am not able to display an image. If I open an image, it does not appear. Are there any constraints for image types?
Command line looks like this:
[cid:56D51F38-24F6-49F9-83C6-B5307AF0A9FC]

I use a Mac early 2015 with Linux installed on VMWare. I am not quite sure if it supports OpenGL 4.3, but I read Macs usually only support OpenGL4.1. However, maybe it might work with Linux.

Kind regards,
Roman


On 08.01.2021, at 19:03, Maurice Tollmien <notifications@github.com<mailto:notifications@github.com>> wrote:

libgl1-mesa-dev

**Comment by RMX0** [comment]
Hi Maurice,

I am not sure if I used it correctly, but I clicked on open and than on Save and entered the name:
[cid:1D71857B-1126-4558-AD38-21A103B00EE7]

I wanted to work with the Gorilla Image and transform it in a similar way as you did with the parrot.
Instead, it returned me the blank png. Do you know how to use it properly?

Kind regards,
Roman


On 09.01.2021, at 17:31, Roman Mühlberger <roman.mbg@hotmail.com<mailto:roman.mbg@hotmail.com>> wrote:

Hi Maurice,

shank you for your help! I installed both packages and the window popped up. However, I am not able to display an image. If I open an image, it does not appear. Are there any constraints for image types?
Command line looks like this:
<Screenshot 2021-01-09 at 17.28.24.png>

I use a Mac early 2015 with Linux installed on VMWare. I am not quite sure if it supports OpenGL 4.3, but I read Macs usually only support OpenGL4.1. However, maybe it might work with Linux.

Kind regards,
Roman


On 08.01.2021, at 19:03, Maurice Tollmien <notifications@github.com<mailto:notifications@github.com>> wrote:

libgl1-mesa-dev

**Comment by RMX0** [comment]
Hi,

while checking my OpeGL version it gave me this reset:
[cid:52A8DAF7-CEF1-4487-809D-8F5BC5831DDF]

I hope the versions are sufficient.

Kind regards,
Roman

On 08.01.2021, at 19:03, Maurice Tollmien <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

Yes, I think I know the issue. Did you install the following packages: libgl1-mesa-dev ?
I found this post with some more information: https://stackoverflow.com/questions/65387167/glfw-pkg-config-error-when-building-a-fyne-app

(sudo apt-get install libgl1-mesa-dev)

If it still doesn't work with libgl1-mesa-dev, try also installing 'xorg-dev'.

Please report back, if it worked :)

**Comment by MauriceGit** [comment]
Hey,

the fact, that everything opens but doesn't show an image points to an insufficient OpenGL version. 
I don't really know, what to do with the "[cid:52A8DAF7-CEF1-4487-809D-8F5BC5831DDF]" to be honest. But (at least under Linux), you can check your OpenGL version with this command: 

glxinfo | grep OpenGL

Look for: "OpenGL core profile version string". What does that say?

As you mentioned the Mac - That is correct, as far as I know, it only supports OpenGL 4.1 unfortunately.
If possible, have a look at your OpenGL version on Linux and try it there (Same machine or different?).

Good luck :)
Kind regards
Maurice

**Comment by RMX0** [comment]
Hey Maurice,

Thanks for your help.
I ran this command in Linux and got this (as shown in the image):
[cid:A13FC07C-1317-47B8-95A1-5E8EF47398D1-L0-001]


It says OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.2.6

I use Linux on the same machine as Mac (via VMWare). Nevertheless, it lets me open and select the photo but no additional window opens that shows the photo to me.

How does it work in general? First open the photo, set the controls and save it afterwards? Does the image appear all the time during the transformation?

Kind regards,
Roman

On 09.01.2021, at 19:19, Maurice Tollmien <notifications@github.com> wrote:

﻿

Hey,

the fact, that everything opens but doesn't show an image points to an insufficient OpenGL version.
I don't really know, what to do with the "[cid:52A8DAF7-CEF1-4487-809D-8F5BC5831DDF]" to be honest. But (at least under Linux), you can check your OpenGL version with this command:

glxinfo | grep OpenGL

Look for: "OpenGL core profile version string". What does that say?

As you mentioned the Mac - That is correct, as far as I know, it only supports OpenGL 4.1 unfortunately.
If possible, have a look at your OpenGL version on Linux and try it there (Same machine or different?).

Good luck :)
Kind regards
Maurice

**Comment by MauriceGit** [comment]
Hey,

I think, Github doesn't show the images any more? I can see the ones from your first posts, but not from the last 3-4 answers it seems. 
But OpenGL Core version 4.5 sounds perfect and should definitely work! There could be issues with hardware accelleration forwarding from VMWare? But no idea really.
Does it say anything on command line when you run the application? Can you run other OpenGL applications fine?

When you run the program, it should immediately show a triangulated image of the Apple per default, even without loading a new image. And the image should change in real-time during the transformations..

Best regards,
Maurice

**Comment by MauriceGit** [comment]
Try one other thing for me:

Clone one of my other projects (shadow maps, should run fine with OpenGL 3.3 and is much simpler): https://github.com/MauriceGit/Variance_Shadow_Maps
cd into the project directory and run ./compile.sh
(The project structure is not really nice, I should port it to go modules at some point...)

Then go into the bin/ folder and run the program. It that works, we know at least, that OpenGL is working fine!

**Comment by RMX0** [comment]
Hi Maurice,

Strange, but I‘ll try to send the images again :) :

Here is the command line output when I open an image:
[cid:DB39EB9C-C6C6-4DB6-829F-16DB7F4E6A21-L0-001]
However, the pop up containing the apple did not show, but just the window with the controls. I tried to simply save as I thought that it works in the background and got an empty png :

[cid:1CFB020B-13FC-4613-8DEB-6FE91532469C-L0-001]

I will try to run your other software tomorrow and also on a different device. Is there anything I should additionally install on Windows? :)

Thanks in advance,
Roman


On 09.01.2021, at 20:44, Maurice Tollmien <notifications@github.com> wrote:

﻿

Hey,

I think, Github doesn't show the images any more? I can see the ones from your first posts, but not from the last 3-4 answers it seems.
But OpenGL Core version 4.5 sounds perfect and should definitely work! There could be issues with hardware accelleration forwarding from VMWare? But no idea really.
Does it say anything on command line when you run the application? Can you run other OpenGL applications fine?

When you run the program, it should immediately show a triangulated image of the Apple per default, even without loading a new image. And the image should change in real-time during the transformations..

Best regards,
Maurice

**Comment by MauriceGit** [comment]
Hi Roman,

I think you should be fine on Windows and shouldn't have to install something else!
Images unfortunately still dont't work - I just get this: "[cid:1CFB020B-13FC-4613-8DEB-6FE91532469C-L0-001]" instead..

Kind regards
Maurice

**Comment by RMX0** [comment]
Hi Maurice, 

I tried a few times on both Linux and Windows, but still keep getting a black window..do you maybe have an idea how to solve this issue? 
I am not sure if southing is not installed or if it is some kind of permissions issue…



I hoped maybe you had some good advice how to solve the issue :) 

Thanks again in advance!
Roman

**Comment by MauriceGit** [comment]
Hi,
I went ahead and installed it on my work computer (Windows) as well to test and everything worked out of the box (go get, go build). I have no idea, what the problem could be any more right now...
You didn't get much further, I guess?
Kind regards,
Maurice

**Comment by RMX0** [comment]
No, unfortunately not. Neither on a Lenovo Computer with Windows running on it nor on Linux or Mac. Maybe there is something I should install manually?

Kind regards,
Roman

On 26.01.2021, at 07:13, Maurice Tollmien <notifications@github.com> wrote:

﻿

Hi,
I went ahead and installed it on my work computer (Windows) as well to test and everything worked out of the box (go get, go build). I have no idea, what the problem could be any more right now...
You didn't get much further, I guess?
Kind regards,
Maurice

**Comment by MauriceGit** [comment]
I'm not aware of anything really, but it does sound like you tried everything and it should have worked...

When I get a chance, I will try it myself from scratch on a different computer to see if something is missing.

I'm sorry this is such a headache...

**Comment by RMX0** [comment]
No, don’t be sorry.. you created a great tool and in fact, I am very grateful that you are very supportive!
Software in general including all it‘s dependencies und underpaying libraries and operating systems can be a headache sometimes ..
I’m trying to progress, but unfortunately I am not familiar with neither Go nor OpenGL.. in particular, I am most interested in the Delauney Edges. Any hint from you was very helpful.

Thanks again for your help!
Roman

On 27.01.2021, at 07:33, Maurice Tollmien <notifications@github.com> wrote:

﻿

I'm not aware of anything really, but it does sound like you tried everything and it should have worked...

When I get a chance, I will try it myself from scratch on a different computer to see if something is missing.

I'm sorry this is such a headache...

**Comment by MauriceGit** [comment]
Thanks a lot for being so understanding. It really seems like we hit a weird combination of hardware, software and libraries, that doesn't work out as easily as expected...

If I have another idea or get to try it on a different computer and find some clues, I will report back!
Maybe with some time, I can create a similar tool without live preview applied to images, that would surely remove the headache around the OpenGL and UI part.

Just to test the Go part, you could clone and run this repository: https://github.com/MauriceGit/FastDelaunayImages

It uses the exact same triangulation/delaunay library but just exports an image of the triangulation depending on different point distributions. This would also be the project, that I would change to use images as color input as well.

No worries about the headache and thanks for putting so much energy in and not abandoning this right away :)

Kind regards,
Maurice

**Comment by RMX0** [comment]
Thank you very much, this would be a great help!
I tried to run it, but unfortunately ran into an error:



On 29.01.2021, at 16:10, Maurice Tollmien <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks a lot for being so understanding. It really seems like we hit a weird combination of hardware, software and libraries, that doesn't work out as easily as expected...

If I have another idea or get to try it on a different computer and find some clues, I will report back!
Maybe with some time, I can create a similar tool without live preview applied to images, that would surely remove the headache around the OpenGL and UI part.

Just to test the Go part, you could clone and run this repository: https://github.com/MauriceGit/FastDelaunayImages

It uses the exact same triangulation/delaunay library but just exports an image of the triangulation depending on different point distributions. This would also be the project, that I would change to use images as color input as well.

No worries about the headache and thanks for putting so much energy in and not abandoning this right away :)

Kind regards,
Maurice

**Comment by RMX0** [comment]
Sorry, I ran into this error:

[cid:5A57AB50-D827-4005-A0EB-2C86910438CE]
Maybe I need to install something there?

Thanks again for your help!

Kind regards,
Roman

On 29.01.2021, at 16:10, Maurice Tollmien <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks a lot for being so understanding. It really seems like we hit a weird combination of hardware, software and libraries, that doesn't work out as easily as expected...

If I have another idea or get to try it on a different computer and find some clues, I will report back!
Maybe with some time, I can create a similar tool without live preview applied to images, that would surely remove the headache around the OpenGL and UI part.

Just to test the Go part, you could clone and run this repository: https://github.com/MauriceGit/FastDelaunayImages

It uses the exact same triangulation/delaunay library but just exports an image of the triangulation depending on different point distributions. This would also be the project, that I would change to use images as color input as well.

No worries about the headache and thanks for putting so much energy in and not abandoning this right away :)

Kind regards,
Maurice

**Comment by MauriceGit** [comment]
The image does not seem to work (can't see it). Can you send me an E-Mail with the image? 
I think, this error should be faster to resolve (without OpenGL bundled in).

Best regards, Maurice

**Comment by MauriceGit** [comment]
Ah, yes, my mistake!
I still had (for debug purposes) the local delaunay library included, instead of the proper one from github. I pushed the fix to the repository. Just update (pull) the repo and it should hopefully work :)

**Comment by MauriceGit** [comment]
A missmatch of the request of OpenGL core version 3.3 but usage of functionality from OpenGL 4.3 seemed to be the issue here. Multisampling is (unfortunately - for now) commented out. Will be reintroduced in a 4.3 release at some point, I think.
